# Markdownlint configuration for Visionary documentation
# Relaxed rules for planning documentation

# Disable line length rule (documentation can be verbose)
MD013: false

# Allow inline HTML (useful for documentation)
MD033: false

# Allow multiple headers with same content
MD024:
  allow_different_nesting: true

# Allow duplicate headers
MD025: false

# Allow missing language in fenced code blocks
MD040: false

# Allow multiple consecutive blank lines (for readability)
MD012: false

# Allow emphasis used instead of headers (for documentation style)
MD036: false
