# Pre-commit hooks for Visionary Planning Repository
# Install with: pip install pre-commit && pre-commit install

repos:
  # Basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.yaml"]
        # Skip Obsidian plugin files and archived content
        exclude: '(\.obsidian/|99-Archive/|\.trash/)'

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types: [yaml]
# Note for implementation phase:
# When moving to actual OpenWebUI implementation, add:
# - ruff (Python linting/formatting)
# - eslint (JavaScript/TypeScript)
# - Additional language-specific hooks
